# grafana/provisioning/datasources/clickhouse.yml
apiVersion: 1

datasources:
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: ozon_analytics
      addCorsHeader: true
      timeout: 30
    secureJsonData:
      password: ''
    editable: true