apiVersion: 1

datasources:
  - name: MongoDB
    type: prometheus
    access: proxy
    url: http://mongodb_exporter:9216
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: GET

  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    editable: true
    jsonData:
      addCorsHeader: true
      defaultDatabase: ozon_analytics
      timeout: 60
    secureJsonData:
      password: admin
    secureJsonFields:
      password: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true